task/IR-8 recover on-chain issuer
energywebfoundation/iam-roles pull request #2
Opened 2022-01-27 15:41 UTC by JGiter

2022-01-28 12:11 UTC, Harasz requested changes

2022-01-28 12:11 UTC, Harasz commented on packages/onChain-RoleEnrollment/src/utils.ts
> +  }
add new line

2022-01-31 06:31 UTC, nichonien reviewed
@JGiter Can you please change the package name, what John suggested ([comment](https://github.com/energywebfoundation/iam-roles/pull/1#pullrequestreview-861890015)). I am following the same for my PR and this would prevent conflict.

2022-01-31 08:09 UTC, Harasz approved these changes

2022-01-31 08:29 UTC, nichonien approved these changes
Thanks @JGiter !

2022-01-31 08:46 UTC, merged